on:
  pull_request:
    branches:
      - master

jobs:
  insist_milestone:
    name: Complain if a milestone isn't set
    runs-on: ubuntu-latest
    # Don't need the expression syntax in the if
    # The if should stop the job from running
    #if: github.event.pull_request.milestone == '{}'
    steps:
    - name: Dump some info
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event.pull_request) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Test conditional
      if: github.event.pull_request.milestone == null
      run: echo "Hey, this needs a milestone!"
    - name: Test other way
      if: github.event.pull_request.milestone != null
      run: echo "This seems to have a milestone!"
